/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.regularUserForms;

import view.regularUserForms.ViewAllCustomers;
import com.documentsystem.model.Businesspartner;
import com.documentsystem.model.Customer;
import com.documentsystem.model.Users;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import logic.Controller;

/**
 *
 * @author Asus
 */
public class UpdateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCustomer
     */
    public UpdateCustomer() {
        initComponents();
        srediFormu();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_customerName = new javax.swing.JTextField();
        jTextField_customerAddress = new javax.swing.JTextField();
        jButton_updateCustomer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_customerID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_createdBy = new javax.swing.JTextField();
        jTextField_busPartner = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Customer Name");

        jLabel2.setText("Address");

        jTextField_customerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_customerAddressActionPerformed(evt);
            }
        });

        jButton_updateCustomer.setText("Update Customer");
        jButton_updateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateCustomerActionPerformed(evt);
            }
        });

        jLabel3.setText("Created by:");

        jLabel4.setText("Business Partner");

        jTextField_customerID.setEnabled(false);

        jLabel5.setText("Customer ID");

        jTextField_createdBy.setEditable(false);
        jTextField_createdBy.setEnabled(false);

        jTextField_busPartner.setEditable(false);
        jTextField_busPartner.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_customerID)
                        .addComponent(jButton_updateCustomer)
                        .addComponent(jTextField_customerAddress)
                        .addComponent(jTextField_customerName, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_busPartner)
                        .addComponent(jTextField_createdBy, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_customerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_createdBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jTextField_busPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_customerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton_updateCustomer)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_customerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_customerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_customerAddressActionPerformed

    private void jButton_updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateCustomerActionPerformed

        try {

            String name = jTextField_customerName.getText().trim();
            String user = jTextField_createdBy.getText().trim();
            int bp = Integer.parseInt(jTextField_busPartner.getText().trim());
            String address = jTextField_customerAddress.getText().trim();
            Businesspartner bpp = new Businesspartner(bp);
            Users u = new Users(user);
          
            Integer customerid = (Integer.parseInt(jTextField_customerID.getText().trim()));

            if (name.equals("")) {
                JOptionPane.showMessageDialog(this, "Populate customer name field please");

            } else {
                Customer c = new Customer(name, address, u, bpp);
                c.setCustomerID(customerid);
                c.setCustomerName(name);
                c.setCustomerAddress(address);
                c.setUser(u);
                c.setBp(bpp);

                Controller.getInstance().updateCustomer(c);

                JOptionPane.showMessageDialog(this, "Customer Updated!");
                this.dispose();
                ViewAllCustomers v = new ViewAllCustomers();
                v.setVisible(true);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Customer NOOOOOOT Updated!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_updateCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_updateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField jTextField_busPartner;
    public javax.swing.JTextField jTextField_createdBy;
    public javax.swing.JTextField jTextField_customerAddress;
    public javax.swing.JTextField jTextField_customerID;
    public javax.swing.JTextField jTextField_customerName;
    // End of variables declaration//GEN-END:variables

    public void srediFormu() {

//        try {
//            java.util.List<Users> lc = Controller.getInstance().getUserList();
//            JComboBox users = new JComboBox();
//            jComboBox_users.removeAllItems();
//            for (Users c : lc) {
//                jComboBox_users.addItem(c);
//                users.addItem(c);
//            }
//
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage());
//        }
//        try {
//            java.util.List<Businesspartner> lc = Controller.getInstance().getPartnerListConditional();
//            JComboBox partners = new JComboBox();
//            jComboBox_busPartners.removeAllItems();
//            for (Businesspartner c : lc) {
//                jComboBox_busPartners.addItem(c);
//                partners.addItem(c);
//            }
//
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage());
//        }
//        Users user = Controller.getInstance().getLogged();
//        String logged = user.getUsername();
//
//        Businesspartner bp = user.getBp();
//        String relatedbp = bp.toString();
//        jTextField_createdBy.setText(logged);
//        jTextField_busPartner.setText(relatedbp);
    }

}
