/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.regularUserForms;

import com.documentsystem.model.Businesspartner;
import com.documentsystem.model.Customer;
import com.documentsystem.model.Users;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logic.Controller;

/**
 *
 * @author Asus
 */
public class ViewAllCustomers extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllCustomers
     */
    public ViewAllCustomers() throws Exception {
        initComponents();
        srediFormu();
        this.setLocationRelativeTo(null);
        jPanel_ViewCustomerDetail.setVisible(false);
    }
    UpdateCustomer updateRow = new UpdateCustomer();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_customers = new javax.swing.JTable();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_viewPartnerInfo = new javax.swing.JButton();
        jPanel_ViewCustomerDetail = new javax.swing.JPanel();
        jTextField_partnerAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_partnerID = new javax.swing.JTextField();
        jTextField_partnerName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable_customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_customers);

        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_viewPartnerInfo.setText("View Customer Info");
        jButton_viewPartnerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewPartnerInfoActionPerformed(evt);
            }
        });

        jTextField_partnerAddress.setEditable(false);
        jTextField_partnerAddress.setEnabled(false);

        jLabel2.setText("Customer Name");

        jLabel3.setText("Address");

        jLabel5.setText("ID");

        jTextField_partnerID.setEditable(false);
        jTextField_partnerID.setEnabled(false);

        jTextField_partnerName.setEditable(false);
        jTextField_partnerName.setEnabled(false);

        javax.swing.GroupLayout jPanel_ViewCustomerDetailLayout = new javax.swing.GroupLayout(jPanel_ViewCustomerDetail);
        jPanel_ViewCustomerDetail.setLayout(jPanel_ViewCustomerDetailLayout);
        jPanel_ViewCustomerDetailLayout.setHorizontalGroup(
            jPanel_ViewCustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ViewCustomerDetailLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel_ViewCustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54)
                .addGroup(jPanel_ViewCustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_partnerName)
                    .addComponent(jTextField_partnerAddress)
                    .addComponent(jTextField_partnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_ViewCustomerDetailLayout.setVerticalGroup(
            jPanel_ViewCustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ViewCustomerDetailLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_ViewCustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_partnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ViewCustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_partnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ViewCustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_partnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_viewPartnerInfo)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jPanel_ViewCustomerDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_update)
                    .addComponent(jButton_delete)
                    .addComponent(jButton_viewPartnerInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_ViewCustomerDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed

        int red = jTable_customers.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select customer!");
        } else {

           CustomerTableModel model = (CustomerTableModel) jTable_customers.getModel();

            String id = model.getValueAt(red, 0).toString();
            int customerid = Integer.parseInt(id);
            try {
                Controller.getInstance().deleteCustomer(customerid);

                JOptionPane.showMessageDialog(this, "Customer Deleted!");
                model.deleteRow(red);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Customer NOOOOT Deleted!!");
            }
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_viewPartnerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewPartnerInfoActionPerformed

        int red = jTable_customers.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select customer!");
        } else {
            CustomerTableModel model = (CustomerTableModel) jTable_customers.getModel();
            Customer c = model.getCustomer(red);
            String id = model.getValueAt(red, 0).toString();
            String customerName = model.getValueAt(red, 1).toString();
            String customerAddress = model.getValueAt(red, 2).toString();
            String user = model.getValueAt(red, 3).toString();
            String bp= model.getValueAt(red, 4).toString();
           
            jPanel_ViewCustomerDetail.setVisible(true);

            jTextField_partnerID.setText(id);
            jTextField_partnerName.setText(customerName);
            jTextField_partnerAddress.setText(customerAddress);
            
            
            jPanel_ViewCustomerDetail.setVisible(true);
        }
    }//GEN-LAST:event_jButton_viewPartnerInfoActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
         int red  =  jTable_customers.getSelectedRow();
      if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select customer!");
        } else {
      CustomerTableModel tm = (CustomerTableModel) jTable_customers.getModel();
      String id = tm.getValueAt(red,0).toString();
      String name = tm.getValueAt(red,1).toString();
      String address = tm.getValueAt(red,2).toString();
      String user = tm.getValueAt(red,3).toString();
      String bp = tm.getValueAt(red,4).toString();
      
          updateRow.setVisible(true);
          updateRow.pack();
          updateRow.setDefaultCloseOperation(UpdateCustomer.DISPOSE_ON_CLOSE);
            this.dispose();
            updateRow.jTextField_customerID.setText(id);
            updateRow.jTextField_customerName.setText(name);
            updateRow.jTextField_customerAddress.setText(address);
            updateRow.jTextField_createdBy.setText(user);
            updateRow.jTextField_busPartner.setText(bp);
            
         
      }
    }//GEN-LAST:event_jButton_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewAllCustomers().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ViewAllCustomers.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    private javax.swing.JButton jButton_viewPartnerInfo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel_ViewCustomerDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_customers;
    public javax.swing.JTextField jTextField_partnerAddress;
    public javax.swing.JTextField jTextField_partnerID;
    public javax.swing.JTextField jTextField_partnerName;
    // End of variables declaration//GEN-END:variables


     public void srediFormu() throws Exception {

        try {
             Users user = Controller.getInstance().getLogged();
            //Customer c = Controller.getInstance().getPartnerList();
            String logged = user.getUsername();
            
            Businesspartner bpid = user.getBp();
            List<Customer> ct = Controller.getInstance().getCustomerListConditional(bpid);
            
            CustomerTableModel model = new  CustomerTableModel (ct);
            jTable_customers.setModel(model);
        } catch (Exception ex) {

            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

      
    }

    
}
