/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.documents;

import com.documentsystem.model.Businesspartner;
import com.documentsystem.model.Customer;
import com.documentsystem.model.Invoice;

import com.documentsystem.model.Products;
import com.documentsystem.model.Users;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import jdk.nashorn.internal.runtime.ListAdapter;

import logic.Controller;

/**
 *
 * @author Asus
 */
public class AddInvoice extends javax.swing.JFrame {

    private final DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
    List<Products> productList;

    /**
     * Creates new form AddInvoice
     */
    public AddInvoice() throws Exception {
        initComponents();
        srediFormu();
//        setModels();
        this.setLocationRelativeTo(null);
        jButton_update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_date = new javax.swing.JTextField();
        jComboBox_customer = new javax.swing.JComboBox();
        jButton_addOrderItem = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_orderItems = new javax.swing.JTable();
        jTextField_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_viewAll = new javax.swing.JButton();
        jTextField_createdBy = new javax.swing.JTextField();
        jTextField_busPartner = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox_customer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_addOrderItem.setText("Add Order Item");
        jButton_addOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addOrderItemActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete Item");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_save.setText("Save Invoice");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jLabel2.setText("Date: dd.MM.yyyy");

        jLabel3.setText("Customer");

        jButton_update.setText("Update Invoice");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jTable_orderItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_orderItems);

        jTextField_id.setEditable(false);
        jTextField_id.setEnabled(false);

        jLabel1.setText("ID");

        jButton_viewAll.setText("View All Invoices");
        jButton_viewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewAllActionPerformed(evt);
            }
        });

        jTextField_createdBy.setEditable(false);
        jTextField_createdBy.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton_viewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addGap(44, 44, 44))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(28, 28, 28)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton_addOrderItem)
                                        .addComponent(jTextField_date)
                                        .addComponent(jComboBox_customer, 0, 194, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38)
                                            .addComponent(jTextField_createdBy)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_busPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_createdBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_busPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton_addOrderItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_save)
                    .addComponent(jButton_update)
                    .addComponent(jButton_viewAll))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addOrderItemActionPerformed

        OrderItemTableModel o = (OrderItemTableModel) jTable_orderItems.getModel();
        o.addOrderItem();

    }//GEN-LAST:event_jButton_addOrderItemActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        int red = jTable_orderItems.getSelectedRow();
        if (red >= 0) {
            OrderItemTableModel model = (OrderItemTableModel) jTable_orderItems.getModel();
            model.deleteOrderItem(red);
        } else {
            JOptionPane.showMessageDialog(this, "Please choose an item!");
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        try {
            OrderItemTableModel model = (OrderItemTableModel) jTable_orderItems.getModel();
            Invoice invoice = model.getInvoice();
            //invoice.setInvoiceID(Integer.parseInt(jTextField_invoiceID.getText().trim()));
            invoice.setInvoiceDate(df.parse(jTextField_date.getText().trim()));
            invoice.setCustomer((Customer) jComboBox_customer.getSelectedItem());
            int bpid = (Integer.parseInt(jTextField_busPartner.getText().trim()));
            Businesspartner bp = new Businesspartner(bpid);
            invoice.setBp(bp);
            Controller.getInstance().saveInvoice(invoice);
            JOptionPane.showMessageDialog(this, "Invoice saved!");
            jButton_update.setEnabled(true);

            jTextField_id.setText("" + invoice.getInvoiceID());
            //jTextField_invoiceID.setEnabled(false);
            jButton_save.setEnabled(false);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        try {
            OrderItemTableModel model = (OrderItemTableModel) jTable_orderItems.getModel();
            Invoice invoice = model.getInvoice();
            // invoice.setInvoiceID(Integer.parseInt(jTextField_id.getText().trim()));
            invoice.setInvoiceDate(df.parse(jTextField_date.getText().trim()));
            invoice.setCustomer((Customer) jComboBox_customer.getSelectedItem());

            Controller.getInstance().updateInvoice(invoice);
            JOptionPane.showMessageDialog(this, "Invoice Updated!");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_viewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewAllActionPerformed
        ViewAllInvoices v;
        try {
            v = new ViewAllInvoices();

            v.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(AddInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose();
    }//GEN-LAST:event_jButton_viewAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddInvoice().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(AddInvoice.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addOrderItem;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_update;
    private javax.swing.JButton jButton_viewAll;
    private javax.swing.JComboBox jComboBox_customer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_orderItems;
    private javax.swing.JTextField jTextField_busPartner;
    private javax.swing.JTextField jTextField_createdBy;
    private javax.swing.JTextField jTextField_date;
    private javax.swing.JTextField jTextField_id;
    // End of variables declaration//GEN-END:variables
private void srediFormu() throws Exception {

        try {
            Users user = Controller.getInstance().getLogged();
            String logged = user.getUsername();
            Businesspartner bpid = user.getBp();
            String relatedbp = bpid.getBpID().toString();
            jTextField_createdBy.setText(logged);
            jTextField_busPartner.setText(relatedbp);
            //int bp = Integer.parseInt(jTextField_busPartner.getText());

            List<Customer> bpp = Controller.getInstance().getCustomerListConditional(bpid);
            jComboBox_customer.setModel(new DefaultComboBoxModel(bpp.toArray()));
            OrderItemTableModel model = new OrderItemTableModel(new Invoice());
            jTable_orderItems.setModel(model);

            List<Products> proList = Controller.getInstance().getProductList();
            JComboBox products = new JComboBox(proList.toArray());
            TableColumn tcProizvod = jTable_orderItems.getColumnModel().getColumn(0);
            tcProizvod.setCellEditor(new DefaultCellEditor(products));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }

    }
}
