/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.documents;

import com.documentsystem.model.Businesspartner;
import com.documentsystem.model.Customer;
import com.documentsystem.model.Invoice;
import com.documentsystem.model.OrderItem;
import com.documentsystem.model.Users;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import logic.Controller;

/**
 *
 * @author Asus
 */
public class ViewAllInvoices extends javax.swing.JFrame {

    /**
     * Creates new form UpdateInvoice
     */
    public ViewAllInvoices() throws Exception {
        initComponents();
        srediFormu();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_invoices = new javax.swing.JTable();
        jButton_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable_invoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_invoices);

        jButton_update.setText("View Details");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_update)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_update)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
      int red  =  jTable_invoices.getSelectedRow();
      if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select the invoice!");
        } else {
     InvoiceTableModel m = (InvoiceTableModel)jTable_invoices.getModel();
     String id = m.getValueAt(red, 0).toString();
     String customerID= m.getValueAt(red, 1).toString();
      Date date= (Date)m.getValueAt(red, 2);
   
    
      
  UpdateInvoice u  ;

  Invoice invoiceID =new Invoice(Integer.parseInt(id)) ;
   invoiceID.setCustomer(new Customer(Integer.parseInt(customerID)));
             // SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
              invoiceID.setInvoiceDate(date);
          try {
             List<OrderItem> ol = Controller.getInstance().getOrderItemList(invoiceID);
                  invoiceID.setOrderItemList(ol);
                  //OrderItemTableModel model = new OrderItemTableModel(ol);
                  u = new UpdateInvoice(invoiceID);
                  u.setVisible(true);
                  
                  //u.jTable_orderItems.setModel(model);
              
          } catch (Exception ex) {
              Logger.getLogger(ViewAllInvoices.class.getName()).log(Level.SEVERE, null, ex);
              ex.printStackTrace();
          }
    
        this.dispose();
       
        
      
      }
    }//GEN-LAST:event_jButton_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewAllInvoices().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ViewAllInvoices.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_invoices;
    // End of variables declaration//GEN-END:variables

public void srediFormu() throws Exception {

        try {
            Users user = Controller.getInstance().getLogged();
            Businesspartner bp = user.getBp();
            
           //Customer customer = new Customer(SOMEBITS);
           
            List<Invoice> ct = Controller.getInstance().getInvoiceListConditional(bp);
            
            InvoiceTableModel model = new  InvoiceTableModel (ct);
            jTable_invoices.setModel(model);
        } catch (Exception ex) {

            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
 
      
    }

}
