/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.documentsystem.model.Businesspartner;
import com.documentsystem.model.City;
import com.documentsystem.model.Positions;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.text.Position;
import logic.Controller;


/**
 *
 * @author Asus
 */
public class AddBusinessPartnerForm extends javax.swing.JFrame {
Businesspartner currentbp;
    /**
     * Creates new form AddBusinessPartnerForm
     */
    public AddBusinessPartnerForm() throws Exception {
        initComponents();
         srediFormu();
         jInternalFrame_addPosition.setVisible(false);
         jButton_addPosition.setEnabled(false);
         //jInternalFrame_addPosition.setVisible(false);
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_partnerName = new javax.swing.JTextField();
        jTextField_partnerAccountNumber = new javax.swing.JTextField();
        jTextField_partnerAddress = new javax.swing.JTextField();
        jComboBox_partnerCity = new javax.swing.JComboBox();
        jButton_savePartner = new javax.swing.JButton();
        jButton_addPosition = new javax.swing.JButton();
        jInternalFrame_addPosition = new javax.swing.JInternalFrame();
        jPanel_internalFrame_addPosition = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_posName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_posDescription = new javax.swing.JTextArea();
        jButton_savePosition = new javax.swing.JButton();
        jTextField_busSysName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_bpID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel_table = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Business Partner");
        setAlwaysOnTop(true);

        jLabel1.setText("Partner Name");

        jLabel2.setText("Address");

        jLabel3.setText("Account number");

        jLabel4.setText("City");

        jTextField_partnerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_partnerAddressActionPerformed(evt);
            }
        });

        jComboBox_partnerCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_savePartner.setText("Save Partner");
        jButton_savePartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_savePartnerActionPerformed(evt);
            }
        });

        jButton_addPosition.setText("Add Position");
        jButton_addPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addPositionActionPerformed(evt);
            }
        });

        jInternalFrame_addPosition.setVisible(true);

        jLabel5.setText("Position Name");

        jLabel6.setText("Description");

        jTextArea_posDescription.setColumns(20);
        jTextArea_posDescription.setRows(5);
        jScrollPane1.setViewportView(jTextArea_posDescription);

        jButton_savePosition.setText("Save Position");
        jButton_savePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_savePositionActionPerformed(evt);
            }
        });

        jTextField_busSysName.setEditable(false);

        jLabel7.setText("Business Partner");

        jTextField_bpID.setEditable(false);
        jTextField_bpID.setEnabled(false);

        jLabel8.setText("BP ID");

        javax.swing.GroupLayout jPanel_internalFrame_addPositionLayout = new javax.swing.GroupLayout(jPanel_internalFrame_addPosition);
        jPanel_internalFrame_addPosition.setLayout(jPanel_internalFrame_addPositionLayout);
        jPanel_internalFrame_addPositionLayout.setHorizontalGroup(
            jPanel_internalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_internalFrame_addPositionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel_internalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel_internalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_bpID)
                    .addComponent(jButton_savePosition)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField_posName)
                    .addComponent(jTextField_busSysName))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel_internalFrame_addPositionLayout.setVerticalGroup(
            jPanel_internalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_internalFrame_addPositionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_internalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_posName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_internalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel_internalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_busSysName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel_internalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_bpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton_savePosition)
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrame_addPositionLayout = new javax.swing.GroupLayout(jInternalFrame_addPosition.getContentPane());
        jInternalFrame_addPosition.getContentPane().setLayout(jInternalFrame_addPositionLayout);
        jInternalFrame_addPositionLayout.setHorizontalGroup(
            jInternalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_internalFrame_addPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame_addPositionLayout.setVerticalGroup(
            jInternalFrame_addPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_internalFrame_addPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel_tableLayout = new javax.swing.GroupLayout(jPanel_table);
        jPanel_table.setLayout(jPanel_tableLayout);
        jPanel_tableLayout.setHorizontalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel_tableLayout.setVerticalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_partnerName)
                                .addComponent(jTextField_partnerAccountNumber)
                                .addComponent(jTextField_partnerAddress)
                                .addComponent(jComboBox_partnerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_savePartner)))
                    .addComponent(jPanel_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame_addPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_addPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_partnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_addPosition))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_partnerAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_partnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox_partnerCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton_savePartner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInternalFrame_addPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_partnerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_partnerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_partnerAddressActionPerformed

    private void jButton_savePartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_savePartnerActionPerformed

         
        try{
      
    
      String name = jTextField_partnerName.getText().trim();
      String accountNumber = jTextField_partnerAccountNumber.getText().trim();
      String address = jTextField_partnerAddress.getText().trim();
      City city = (City)jComboBox_partnerCity.getSelectedItem();
      
      if(name.equals("")){
       JOptionPane.showMessageDialog(this, "Populate bussiness system name field please");

      }else{

       currentbp= new Businesspartner(name, new City(city.getZip(), city.getCityName()), accountNumber, address);
      
      Controller.getInstance().addPartner(currentbp);
  
      JOptionPane.showMessageDialog(this, "Business Partner Saved!");
      jButton_addPosition.setEnabled(true);
//jInternalFrame_addPosition.setVisible(true); 
    }
        }
    catch (Exception ex)
    {
      JOptionPane.showMessageDialog(this, "Business Partner NOOOOOOT Saved!");
      ex.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_savePartnerActionPerformed

    private void jButton_addPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addPositionActionPerformed
      jInternalFrame_addPosition.setVisible(true);
       String bsname = currentbp.getName();
       
      // Businesspartner bp = new Businesspartner();
       // Integer bpid = bp.getBpID();
       // String id = bpid.toString();
      
        jTextField_posName.setText("");
        jTextArea_posDescription.setText("");
        jTextField_busSysName.setText(bsname);
       jTextField_bpID.setText(""+currentbp.getBpID());
    
     
    }//GEN-LAST:event_jButton_addPositionActionPerformed

    private void jButton_savePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_savePositionActionPerformed
        
        try {
           String posName=jTextField_posName.getText().trim();
           String posDesc = jTextArea_posDescription.getText().trim();
          
           if(posName.equals("")){
       JOptionPane.showMessageDialog(this, "Populate position name field please");

      }else{
            Positions p = new Positions();
        p.setPosName(posName);
        p.setPosDescription(posDesc);
        //p.setBusinessPartner();
        
        p.setBusinessPartner(currentbp);
        
        
        Controller.getInstance().addPosition(p);
        JOptionPane.showMessageDialog(this, "Position Saved!");
          
        jInternalFrame_addPosition.dispose();
              
        
         }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Position Not Saved!");
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_jButton_savePositionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBusinessPartnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBusinessPartnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBusinessPartnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBusinessPartnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddBusinessPartnerForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(AddBusinessPartnerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addPosition;
    private javax.swing.JButton jButton_savePartner;
    private javax.swing.JButton jButton_savePosition;
    private javax.swing.JComboBox jComboBox_partnerCity;
    private javax.swing.JInternalFrame jInternalFrame_addPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel_internalFrame_addPosition;
    private javax.swing.JPanel jPanel_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_posDescription;
    private javax.swing.JTextField jTextField_bpID;
    private javax.swing.JTextField jTextField_busSysName;
    private javax.swing.JTextField jTextField_partnerAccountNumber;
    private javax.swing.JTextField jTextField_partnerAddress;
    private javax.swing.JTextField jTextField_partnerName;
    private javax.swing.JTextField jTextField_posName;
    // End of variables declaration//GEN-END:variables



 private void srediFormu() throws Exception
  {
    try
    {
    
        List<City> lc = Controller.getInstance().getCityList();
      JComboBox cityTable = new JComboBox();
      jComboBox_partnerCity.removeAllItems();
      for (City c : lc) {
        jComboBox_partnerCity.addItem(c);
        cityTable.addItem(c);
      }
    
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    
//    List<Positions> pos = Controller.getInstance().getPositionList();
//       PositionsTableModel model = new PositionsTableModel(pos);
//      jTable_positionsList.setModel(model);
//      
           
            
       }  
  }



