/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.documentsystem.model.Businesspartner;
import com.documentsystem.model.Role;
import com.documentsystem.model.Users;
import view.regularUserForms.ViewAllCustomers;
import java.util.logging.Level;
import java.util.logging.Logger;
import logic.Controller;
import view.documents.AddInvoice;
import view.documents.AllInvoices;
import view.documents.ViewAllInvoices;
import view.regularUserForms.CreateCustomer;

/**
 *
 * @author Asus
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public void assignMenu(Role loggedrole) {
        // Users user = new Users();
        //  Role role = user.getRoleFk();
//    if (loggedrole.getRoleID()!= 1){
//    jMenu_businessPartners.setEnabled(false);
//   
//   
//    }
        if (loggedrole.getRoleID() != 1 && loggedrole.getRoleID() != 2) {
            jMenu_administration.setEnabled(false);
            //jMenu_myAccount.setEnabled(false);

        } else if (loggedrole.getRoleID() == 2) {
            jMenu_administration.setEnabled(true);
            jMenu_BP.setEnabled(false);
            jMenu_user.setEnabled(true);
            jMenu_myAccount.setEnabled(true);

        } else {

            jMenu_administration.setEnabled(true);
            jMenu_myAccount.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_loggedIn = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_file = new javax.swing.JMenu();
        jMenuItem_logout = new javax.swing.JMenuItem();
        jMenuItem_exit = new javax.swing.JMenuItem();
        jMenu_administration = new javax.swing.JMenu();
        jMenu_BP = new javax.swing.JMenu();
        jMenuItem_NewBusinessPartner = new javax.swing.JMenuItem();
        jMenuItem_viewAllBP = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_viewPositions = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu_user = new javax.swing.JMenu();
        jMenuItem_addNewUser = new javax.swing.JMenuItem();
        jMenuItem_ViewAllUsers = new javax.swing.JMenuItem();
        jMenu_myAccount = new javax.swing.JMenu();
        jMenu_customers = new javax.swing.JMenu();
        jMenuItem_addCustomr = new javax.swing.JMenuItem();
        jMenuItem_viewCustomers = new javax.swing.JMenuItem();
        jMenu_documents = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_invoicesView = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Logged in user:");

        jTextField_loggedIn.setEditable(false);
        jTextField_loggedIn.setEnabled(false);
        jTextField_loggedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_loggedInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_loggedIn, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_loggedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenu_file.setText("File");

        jMenuItem_logout.setText("Logout");
        jMenuItem_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_logoutActionPerformed(evt);
            }
        });
        jMenu_file.add(jMenuItem_logout);

        jMenuItem_exit.setText("Exit");
        jMenuItem_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exitActionPerformed(evt);
            }
        });
        jMenu_file.add(jMenuItem_exit);

        jMenuBar1.add(jMenu_file);

        jMenu_administration.setText("Administration");

        jMenu_BP.setText("Business Partners");

        jMenuItem_NewBusinessPartner.setText("New Business Partner");
        jMenuItem_NewBusinessPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NewBusinessPartnerActionPerformed(evt);
            }
        });
        jMenu_BP.add(jMenuItem_NewBusinessPartner);

        jMenuItem_viewAllBP.setText("View all Business Partners");
        jMenuItem_viewAllBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_viewAllBPActionPerformed(evt);
            }
        });
        jMenu_BP.add(jMenuItem_viewAllBP);

        jMenu_administration.add(jMenu_BP);
        jMenu_administration.add(jSeparator2);

        jMenuItem_viewPositions.setText("View all Positions");
        jMenuItem_viewPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_viewPositionsActionPerformed(evt);
            }
        });
        jMenu_administration.add(jMenuItem_viewPositions);
        jMenu_administration.add(jSeparator1);

        jMenu_user.setText("Users");

        jMenuItem_addNewUser.setText("Add new user");
        jMenuItem_addNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addNewUserActionPerformed(evt);
            }
        });
        jMenu_user.add(jMenuItem_addNewUser);

        jMenuItem_ViewAllUsers.setText("View all users");
        jMenuItem_ViewAllUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ViewAllUsersActionPerformed(evt);
            }
        });
        jMenu_user.add(jMenuItem_ViewAllUsers);

        jMenu_administration.add(jMenu_user);

        jMenuBar1.add(jMenu_administration);

        jMenu_myAccount.setText("My Account");

        jMenu_customers.setText("Customers");

        jMenuItem_addCustomr.setText("Add New Customer");
        jMenuItem_addCustomr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addCustomrActionPerformed(evt);
            }
        });
        jMenu_customers.add(jMenuItem_addCustomr);

        jMenuItem_viewCustomers.setText("View all Customers");
        jMenuItem_viewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_viewCustomersActionPerformed(evt);
            }
        });
        jMenu_customers.add(jMenuItem_viewCustomers);

        jMenu_myAccount.add(jMenu_customers);

        jMenu_documents.setText("Documents");

        jMenu2.setText("Invoices");

        jMenuItem_invoicesView.setText("Add New Invoice");
        jMenuItem_invoicesView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_invoicesViewActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_invoicesView);

        jMenuItem1.setText("View All Invoices");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenu_documents.add(jMenu2);

        jMenu3.setText("Orders");
        jMenu_documents.add(jMenu3);

        jMenu_myAccount.add(jMenu_documents);

        jMenuBar1.add(jMenu_myAccount);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 748, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 541, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_NewBusinessPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NewBusinessPartnerActionPerformed
        AddBusinessPartnerForm abpf;
        try {
            abpf = new AddBusinessPartnerForm();
            abpf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem_NewBusinessPartnerActionPerformed

    private void jMenuItem_viewAllBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_viewAllBPActionPerformed
        ViewAllBusinessPartners va;
        try {
            va = new ViewAllBusinessPartners();
            va.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem_viewAllBPActionPerformed

    private void jMenuItem_addNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addNewUserActionPerformed

        AddUser au;
        try {
            au = new AddUser();
            au.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jMenuItem_addNewUserActionPerformed

    private void jMenuItem_ViewAllUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ViewAllUsersActionPerformed

        ViewAllUsersForm vu;
        try {
            vu = new ViewAllUsersForm();
            vu.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem_ViewAllUsersActionPerformed

    private void jMenuItem_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_logoutActionPerformed
        Login l = new Login(this, true);

        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_logoutActionPerformed

    private void jMenuItem_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_exitActionPerformed

    private void jMenuItem_viewPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_viewPositionsActionPerformed
        ViewAllPositions vp;
        try {
            vp = new ViewAllPositions();
            vp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem_viewPositionsActionPerformed

    private void jMenuItem_addCustomrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addCustomrActionPerformed
        
        try {
            CreateCustomer cc;
            cc = new CreateCustomer();
            cc.setVisible(true);
//              Users u = new Users();
//            //u.setUsername(username);
//            Users user = Controller.getInstance().login(u);
//            String logged = user.getName() + " " + user.getLastName();
//Businesspartner relatedbp = user.getBp();
//          cc.jTextField_createdBy.setText(logged);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jMenuItem_addCustomrActionPerformed

    private void jMenuItem_viewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_viewCustomersActionPerformed
        ViewAllCustomers vc;
        try {
            vc = new ViewAllCustomers();
            vc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jMenuItem_viewCustomersActionPerformed

    private void jMenuItem_invoicesViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_invoicesViewActionPerformed
        AddInvoice ai;
        try {
            ai = new AddInvoice();
            ai.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem_invoicesViewActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViewAllInvoices all;
        try {
            all = new ViewAllInvoices();
            all.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField_loggedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_loggedInActionPerformed
        Users u = new Users();
        Users user;
        try {
            user = Controller.getInstance().login(u);
            String logged = user.getUsername();

        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jTextField_loggedInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_NewBusinessPartner;
    private javax.swing.JMenuItem jMenuItem_ViewAllUsers;
    private javax.swing.JMenuItem jMenuItem_addCustomr;
    private javax.swing.JMenuItem jMenuItem_addNewUser;
    private javax.swing.JMenuItem jMenuItem_exit;
    private javax.swing.JMenuItem jMenuItem_invoicesView;
    private javax.swing.JMenuItem jMenuItem_logout;
    private javax.swing.JMenuItem jMenuItem_viewAllBP;
    private javax.swing.JMenuItem jMenuItem_viewCustomers;
    private javax.swing.JMenuItem jMenuItem_viewPositions;
    private javax.swing.JMenu jMenu_BP;
    private javax.swing.JMenu jMenu_administration;
    private javax.swing.JMenu jMenu_customers;
    private javax.swing.JMenu jMenu_documents;
    private javax.swing.JMenu jMenu_file;
    private javax.swing.JMenu jMenu_myAccount;
    private javax.swing.JMenu jMenu_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JTextField jTextField_loggedIn;
    // End of variables declaration//GEN-END:variables
}
