/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.documentsystem.model.Businesspartner;
import com.documentsystem.model.City;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import logic.Controller;
import logic.PartnerCollection;

/**
 *
 * @author Asus
 */
public class ViewAllBusinessPartners extends javax.swing.JFrame {

    int bpID;

    /**
     * Creates new form ViewAllBusinessPartners
     */
    public ViewAllBusinessPartners() throws Exception {
        initComponents();
        srediFormu();
        jPanel_ViewBusPartnerDetail.setVisible(false);
        this.setLocationRelativeTo(null);
    }
    UpdateBusPartner updateRow = new UpdateBusPartner();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_UpdatePartner = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_viewAllBusPartners = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton_delete = new javax.swing.JButton();
        jButton_viewPartnerInfo = new javax.swing.JButton();
        jPanel_ViewBusPartnerDetail = new javax.swing.JPanel();
        jTextField_partnerAccountNumber = new javax.swing.JTextField();
        jTextField_partnerAddress = new javax.swing.JTextField();
        jComboBox_partnerCity = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_partnerID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_partnerName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View All Business Partners");
        setAlwaysOnTop(true);

        jButton_UpdatePartner.setText("Update");
        jButton_UpdatePartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdatePartnerActionPerformed(evt);
            }
        });

        jTable_viewAllBusPartners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_viewAllBusPartners);

        jLabel1.setText("Partners:");

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_viewPartnerInfo.setText("View Partner Info");
        jButton_viewPartnerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewPartnerInfoActionPerformed(evt);
            }
        });

        jTextField_partnerAccountNumber.setEditable(false);
        jTextField_partnerAccountNumber.setEnabled(false);

        jTextField_partnerAddress.setEditable(false);
        jTextField_partnerAddress.setEnabled(false);

        jComboBox_partnerCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_partnerCity.setEnabled(false);

        jLabel2.setText("Partner Name");

        jLabel3.setText("Address");

        jLabel5.setText("ID");

        jTextField_partnerID.setEditable(false);
        jTextField_partnerID.setEnabled(false);

        jLabel4.setText("Account number");

        jLabel6.setText("City");

        jTextField_partnerName.setEditable(false);
        jTextField_partnerName.setEnabled(false);

        javax.swing.GroupLayout jPanel_ViewBusPartnerDetailLayout = new javax.swing.GroupLayout(jPanel_ViewBusPartnerDetail);
        jPanel_ViewBusPartnerDetail.setLayout(jPanel_ViewBusPartnerDetailLayout);
        jPanel_ViewBusPartnerDetailLayout.setHorizontalGroup(
            jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ViewBusPartnerDetailLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_partnerName)
                    .addComponent(jTextField_partnerAccountNumber)
                    .addComponent(jTextField_partnerAddress)
                    .addComponent(jComboBox_partnerCity, 0, 167, Short.MAX_VALUE)
                    .addComponent(jTextField_partnerID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_ViewBusPartnerDetailLayout.setVerticalGroup(
            jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ViewBusPartnerDetailLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_partnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_partnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_partnerAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_partnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ViewBusPartnerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_partnerCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_UpdatePartner)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_viewPartnerInfo))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel_ViewBusPartnerDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_UpdatePartner)
                    .addComponent(jButton_delete)
                    .addComponent(jButton_viewPartnerInfo))
                .addGap(32, 32, 32)
                .addComponent(jPanel_ViewBusPartnerDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdatePartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdatePartnerActionPerformed
        int red = jTable_viewAllBusPartners.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select business partner!");
        } else {
            BusinessPartnerTableModel model = (BusinessPartnerTableModel) jTable_viewAllBusPartners.getModel();
            Businesspartner bp = model.getPartner(red);
            String id = model.getValueAt(red, 0).toString();
            String companyName = model.getValueAt(red, 1).toString();
            String companyCity = model.getValueAt(red, 2).toString();
            String accountNumber = model.getValueAt(red, 3).toString();
            String address = model.getValueAt(red, 4).toString();
           // String zip = model.getValueAt(red, 5).toString();
            
            updateRow.setVisible(true);
            updateRow.pack();
            updateRow.setDefaultCloseOperation(UpdateBusPartner.DISPOSE_ON_CLOSE);
            this.dispose();

            updateRow.jTextField_partnerID.setText(id);
            updateRow.jTextField_partnerName.setText(companyName);
            updateRow.jTextField_partnerAccountNumber.setText(accountNumber);
            updateRow.jTextField_partnerAddress.setText(address);
            updateRow.jComboBox_partnerCity.setSelectedItem(companyCity);
        }

        //updateRow.jTextField_partnerName.setText(zip);
        // Controller.getInstance().put("izabrani_partner", bp);
        // UpdateBusPartner updatebp = new UpdateBusPartner();
        //updatebp.setVisible(true);

    }//GEN-LAST:event_jButton_UpdatePartnerActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed

        int red = jTable_viewAllBusPartners.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select business partner!");
        } else {

            BusinessPartnerTableModel model = (BusinessPartnerTableModel) jTable_viewAllBusPartners.getModel();

            String id = model.getValueAt(red, 0).toString();
            int bpid = Integer.parseInt(id); 
            try {
                Controller.getInstance().deletePartner(bpid);

                JOptionPane.showMessageDialog(ViewAllBusinessPartners.this, "Business Partner Deleted!");
                model.deleteRow(red);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(ViewAllBusinessPartners.this, "Business Partner NOOOOT Deleted!!");
            }
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_viewPartnerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewPartnerInfoActionPerformed

        int red = jTable_viewAllBusPartners.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select business partner!");
        } else {
            BusinessPartnerTableModel model = (BusinessPartnerTableModel) jTable_viewAllBusPartners.getModel();
            Businesspartner bp = model.getPartner(red);
            String id = model.getValueAt(red, 0).toString();
            String companyName = model.getValueAt(red, 1).toString();
            String companyCity = model.getValueAt(red, 2).toString();
            String accountNumber = model.getValueAt(red, 3).toString();
            String address = model.getValueAt(red, 4).toString();

            // String zip = model.getValueAt(index, 4).toString();
            jPanel_ViewBusPartnerDetail.setVisible(true);

            jTextField_partnerID.setText(id);
            jTextField_partnerName.setText(companyName);
            jTextField_partnerAccountNumber.setText(accountNumber);
            jTextField_partnerAddress.setText(address);
            jComboBox_partnerCity.setSelectedItem(companyCity);
        }
    }//GEN-LAST:event_jButton_viewPartnerInfoActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllBusinessPartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllBusinessPartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllBusinessPartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllBusinessPartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewAllBusinessPartners().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ViewAllBusinessPartners.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_UpdatePartner;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_viewPartnerInfo;
    public javax.swing.JComboBox jComboBox_partnerCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel_ViewBusPartnerDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_viewAllBusPartners;
    public javax.swing.JTextField jTextField_partnerAccountNumber;
    public javax.swing.JTextField jTextField_partnerAddress;
    public javax.swing.JTextField jTextField_partnerID;
    public javax.swing.JTextField jTextField_partnerName;
    // End of variables declaration//GEN-END:variables

    public void srediFormu() throws Exception {

        try {
            List<Businesspartner> bp = Controller.getInstance().getPartnerList();
            //jComboBox_partnerList.setModel(new DefaultComboBoxModel(bp.toArray()));
            BusinessPartnerTableModel model = new BusinessPartnerTableModel(bp);
            jTable_viewAllBusPartners.setModel(model);
        } catch (Exception ex) {

            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

        try {
            java.util.List<City> lc = Controller.getInstance().getCityList();
            JComboBox cityTable = new JComboBox();
            jComboBox_partnerCity.removeAllItems();
            for (City c : lc) {
                jComboBox_partnerCity.addItem(c);
                cityTable.addItem(c);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

}
