/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.documentsystem.model.Businesspartner;
import com.documentsystem.model.City;
import com.documentsystem.model.Positions;
import com.documentsystem.model.Role;
import com.documentsystem.model.Users;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.text.Position;
import logic.Controller;

/**
 *
 * @author Asus
 */
public class ViewAllUsersForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllUsersForm
     */
    public ViewAllUsersForm() throws Exception {
        initComponents();
        srediFormu();
        jPanel_userInfo.setVisible(false);
        this.setLocationRelativeTo(null);
    }
    UpdateUser updateRow = new UpdateUser();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_Update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_viewInfo = new javax.swing.JButton();
        jPanel_userInfo = new javax.swing.JPanel();
        jTextField_userID = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jTextField_lastName = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_role = new javax.swing.JComboBox();
        jComboBox_pos = new javax.swing.JComboBox();
        jComboBox_businessPartner = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_allUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Users:");

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_viewInfo.setText("View User Info");
        jButton_viewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewInfoActionPerformed(evt);
            }
        });

        jTextField_userID.setEditable(false);
        jTextField_userID.setEnabled(false);

        jTextField_name.setEditable(false);
        jTextField_name.setEnabled(false);

        jTextField_lastName.setEditable(false);
        jTextField_lastName.setEnabled(false);

        jTextField_username.setEditable(false);
        jTextField_username.setEnabled(false);

        jLabel2.setText("User ID");

        jLabel3.setText("Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Username");

        jLabel6.setText("Role");

        jLabel7.setText("Position");

        jComboBox_role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_role.setEnabled(false);
        jComboBox_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_roleActionPerformed(evt);
            }
        });

        jComboBox_pos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_pos.setEnabled(false);

        jComboBox_businessPartner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_businessPartner.setEnabled(false);

        jLabel8.setText("Business Partner");

        javax.swing.GroupLayout jPanel_userInfoLayout = new javax.swing.GroupLayout(jPanel_userInfo);
        jPanel_userInfo.setLayout(jPanel_userInfoLayout);
        jPanel_userInfoLayout.setHorizontalGroup(
            jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userInfoLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_businessPartner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_username)
                    .addComponent(jTextField_lastName)
                    .addComponent(jTextField_name)
                    .addComponent(jTextField_userID)
                    .addComponent(jComboBox_role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_pos, 0, 121, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel_userInfoLayout.setVerticalGroup(
            jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_businessPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTable_allUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_allUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton_Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_viewInfo)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Update)
                    .addComponent(jButton_delete)
                    .addComponent(jButton_viewInfo))
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(jPanel_userInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        int red = jTable_allUsers.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select user!");
        } else {
            UsersTableModel utm = (UsersTableModel) jTable_allUsers.getModel();
            Users u = utm.getUser(red);
            String id = utm.getValueAt(red, 0).toString();
            String name = utm.getValueAt(red, 1).toString();
            String lastname = utm.getValueAt(red, 2).toString();
            String username = utm.getValueAt(red, 3).toString();
            // String password = utm.getValueAt(red, 4).toString();
            String role = utm.getValueAt(red, 4).toString();
            String pos = utm.getValueAt(red, 5).toString();
            String bp = utm.getValueAt(red, 6).toString();
            updateRow.setVisible(true);
            updateRow.pack();
            updateRow.setDefaultCloseOperation(UpdateUser.DISPOSE_ON_CLOSE);
            this.dispose();

            updateRow.jTextField_userID.setText(id);
            updateRow.jTextField_name.setText(name);
            updateRow.jTextField_lastName.setText(lastname);
            updateRow.jTextField_username.setText(username);
           updateRow.jComboBox_role.setSelectedItem(role);
            updateRow.jComboBox_pos.setSelectedItem(pos);
            updateRow.jComboBox_role.setSelectedItem(role);
            updateRow.jComboBox_bp.setSelectedItem(bp);
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_viewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewInfoActionPerformed
        int red = jTable_allUsers.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select user!");
        } else {
            UsersTableModel utm = (UsersTableModel) jTable_allUsers.getModel();
            Users u = utm.getUser(red);

            String id = utm.getValueAt(red, 0).toString();
            String name = utm.getValueAt(red, 1).toString();
            String lastname = utm.getValueAt(red, 2).toString();
            String username = utm.getValueAt(red, 3).toString();
            // String password = utm.getValueAt(red, 4).toString();
            String role = utm.getValueAt(red, 4).toString();
            String pos = utm.getValueAt(red, 5).toString();
            String bp = utm.getValueAt(red, 6).toString();
            jPanel_userInfo.setVisible(true);
            jTextField_userID.setText(id);
            jTextField_name.setText(name);
            jTextField_lastName.setText(lastname);
            jTextField_username.setText(username);
            jComboBox_role.setSelectedItem(role);
            jComboBox_pos.setSelectedItem(pos);
            jComboBox_businessPartner.setSelectedItem(bp);
        }
    }//GEN-LAST:event_jButton_viewInfoActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        int red = jTable_allUsers.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Please select user!");
        } else {

            UsersTableModel utm = (UsersTableModel) jTable_allUsers.getModel();
            String id = utm.getValueAt(red, 0).toString();
            int userID = Integer.parseInt(id);

            try {
                Controller.getInstance().deleteUser(userID);

                JOptionPane.showMessageDialog(ViewAllUsersForm.this, "User Deleted!");
                utm.deleteRow(red);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(ViewAllUsersForm.this, "User NOOOOT Deleted!!");
            }
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jComboBox_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_roleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewAllUsersForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ViewAllUsersForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Update;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_viewInfo;
    private javax.swing.JComboBox jComboBox_businessPartner;
    private javax.swing.JComboBox jComboBox_pos;
    private javax.swing.JComboBox jComboBox_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel_userInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_allUsers;
    private javax.swing.JTextField jTextField_lastName;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_userID;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables

    public void srediFormu() throws Exception {

        try {
            List<Users> u = Controller.getInstance().getUserList();

            UsersTableModel model = new UsersTableModel(u);
            jTable_allUsers.setModel(model);
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

        try {
            java.util.List<Role> rc = Controller.getInstance().getRoleList();
            JComboBox roles = new JComboBox();
            jComboBox_role.removeAllItems();
            for (Role c : rc) {
                jComboBox_role.addItem(c);
                roles.addItem(c);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }

        try {
            java.util.List<Positions> lp = Controller.getInstance().getPositionList();
            JComboBox posi = new JComboBox();
            jComboBox_pos.removeAllItems();
            for (Positions p : lp) {
                jComboBox_pos.addItem(p);
                posi.addItem(p);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }

        try {
            java.util.List<Businesspartner> bp = Controller.getInstance().getPartnerList();
            JComboBox posi = new JComboBox();
            jComboBox_businessPartner.removeAllItems();
            for (Businesspartner p : bp) {
                jComboBox_businessPartner.addItem(p);
                posi.addItem(p);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }

    }

}
